"""
Async database engine and session factory for the ORM models to use
"""

import os

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.config import settings

"""
Set the database url to an env variable so that is can be easily changed
"""

DATABASE_URL = settings.database_url

#echo = true enables the logging of all SQL statements generated by SQLAlchemy
engine = create_async_engine(DATABASE_URL, echo=True)

#expire_on_commit=False prevents the session from expiring objects after a commit
AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit=False)
